GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/691610783565927a2e948483

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/691631013c7e7f4a713e93c5

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "cesar2",
    "number": "12-542-54431"
}